config/routes.rb
Rails.application.routes.draw do
  resources :bounties
  resources :sessions, only: :create
  resources :users, only: %i[ create update edit destroy ]

  get "login" => "sessions#new", as: :login
  get "logout" => "sessions#destroy", as: :logout
  get "signup" => "users#new", as: :signup

  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  post "geocoding" => "geocoding#create", as: :geocoding

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "welcome#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bounty.rb
class Bounty < ApplicationRecord
  belongs_to :user

  validates :title, :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }

  def postal_code
    super || user.postal_code
  end

  def user_email
    user.email
  end

  def user_name
    user.name
  end
end

app/models/permission.rb
class Permission
  class << self
    def for(resource:, current_user:)
      type_for(resource).new(resource:, current_user:)
    end

    private

    def type_for(resource)
      "#{resource.class.name}Permission".constantize
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, complex_password: true

  normalizes :email, with: ->(email) { email.strip.downcase }

  has_many :bounties, dependent: :destroy

  def name
    return email if first_name.blank?
    "#{first_name} #{last_name[0]}."
  end

  def initials
    return unless first_name.present? && last_name.present?
    "#{first_name[0]}#{last_name[0]}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from "ActiveRecord::RecordNotFound" do
    redirect_to root_path, alert: "We couldn't find that page."
  end

  helper_method :current_user, :permission

  private

  def require_user
    return if current_user
    redirect_to login_path, alert: "You must be logged in"
  end

  def authorize!(resource)
    return if permission(resource).allowed?(action_name:)
    redirect_to root_path, alert: "You are not allowed to do that."
  end

  def permission(resource)
    @permission ||= Permission.for(resource:, current_user:)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id]) if session[:current_user_id]
  end
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  before_action :require_user
  before_action :load_and_authorize_bounty, only: %i[ edit update destroy ]

  def index
    @bounties = Bounty.all
  end

  def show
    @bounty = Bounty.find(params.expect(:id))
  end

  def new
    @bounty = current_user.bounties.build
  end

  def create
    @bounty = current_user.bounties.build(bounty_params)

    respond_to do |format|
      if @bounty.save
        format.html { redirect_to @bounty, notice: "Bounty was successfully created." }
        format.json { render :show, status: :created, location: @bounty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bounty.update(bounty_params)
        format.html { redirect_to @bounty, notice: "Bounty was successfully updated." }
        format.json { render :show, status: :ok, location: @bounty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bounty.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bounty.destroy!

    respond_to do |format|
      format.html { redirect_to bounties_path, status: :see_other, notice: "Bounty was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def load_and_authorize_bounty
    @bounty = current_user.bounties.find(params.expect(:id))
    authorize!(@bounty)
  end

  def bounty_params
    params.expect(bounty: [ :title, :amount, :postal_code ])
  end
end

app/controllers/geocoding_controller.rb
require "net/http"

class GeocodingController < ApplicationController
  def create
    uri = URI("http://api.geonames.org/findNearbyPostalCodesJSON")
    uri.query = { lat:, lng:, username: :joemsak }.to_query
    res = Net::HTTP.get(uri)
    postal_code = JSON(res)["postalCodes"][0]["postalCode"]

    current_user.update!(lat:, lng:, postal_code:)

    render json: { lat:, lng:, postal_code: }
  end

  private

  def lat
    params.expect(:lat)
  end

  def lng
    params.expect(:lng)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  rescue_from "ActionController::ParameterMissing" do
    redirect_to login_path, alert: "Incorrect email and/or password"
  end

  def create
    user = User.find_by(email: params.expect(:email))

    if user.authenticate(params.expect(:password))
      session[:current_user_id] = user.id
      redirect_to bounties_path, notice: "Welcome back"
    else
      render :new, alert: "Incorrect email and/or password"
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path, notice: "You logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, :load_and_authorize_user,
    only: %i[ edit update ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user_id] = @user.id
        format.html { redirect_to bounties_path, notice: "Welcome to Bounty Hunter!" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def load_and_authorize_user
    @user = User.find(params.expect(:id))
    authorize!(@user)
  end

  def user_params
    params.expect(user: [ :email, :password, :postal_code, :first_name, :last_name ])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bounties/_bounty.html.erb
<tr id="<%= dom_id bounty %>">
  <td><%= bounty.title %></td>
  <td><%= number_to_currency(bounty.amount) %></td>
  <td><%= bounty.user_name %></td>
  <td><%= bounty.postal_code %></td>
  <td><%= link_to "details", bounty %></td>
</tr>

app/views/bounties/_form.html.erb
<%= form_with(model: bounty) do |f| %>
  <%= render "shared/errors", errors: bounty.errors %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :amount %>

  <div class="flex">
    <div class="py-2 px-4 bg-gray-300 font-bold border border-r-0">$</div>
    <%= f.text_field :amount %>
  </div>

  <%= f.label :postal_code %>
  <%= f.text_field :postal_code %>

  <div class="mt-8 md:flex md:items-center md:gap-1">
    <%= f.submit "Save" %>

    <div class="mt-4 md:m-0 shrink-0">
      or <%= link_to "cancel", bounty.new_record? ? bounties_path : bounty %>
    </div>
  </div>
<% end %>

app/views/bounties/edit.html.erb
<% content_for :title, "Editing bounty" %>

<h1>Editing bounty</h1>

<%= render "form", bounty: @bounty %>

app/views/bounties/index.html.erb
<% content_for :title, "Bounties" %>

<h1>Bounties</h1>

<%= button_to "&plus; Post a bounty".html_safe, new_bounty_path, method: :get, class: "mt-4" %>

<div class="w-full overflow-x-auto">
  <table
    id="bounties"
    class="mt-4"
    data-controller="geocoding"
    data-geocoding-postal-code-value="<%= current_user.postal_code %>"
  >
    <%= render @bounties %>
  </table>
</div>

app/views/bounties/new.html.erb
<% content_for :title, "Post your bounty" %>

<h1>Post your bounty</h1>

<%= render "form", bounty: @bounty %>

app/views/bounties/show.html.erb
<h1>Bounty posted by <%= @bounty.user_name %> in <%= @bounty.postal_code %></h1>

<dl class="mt-4">
  <dt>Title</dt>
  <dd><%= @bounty.title %></dd>

  <dt>Amount</dt>
  <dd><%= number_to_currency(@bounty.amount) %></dd>
</dl>

<div class="mt-4 flex items-center gap-1">
  <%= link_to "Browse all", bounties_path %>
  <% if permission(@bounty).allowed?(action_name: :edit) %>
    | <%= link_to "Edit", edit_bounty_path(@bounty) %> |
    <%= link_to "Delete", @bounty, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  <% end %>
</div>

app/views/gigs/_form.html.erb
<%= form_with(model: gig) do |form| %>
  <% if gig.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gig.errors.count, "error") %> prohibited this gig from being saved:</h2>

      <ul>
        <% gig.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :bounty, style: "display: block" %>
    <%= form.text_field :bounty %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% bg_color = notice ? "bg-green-600" : "bg-red-600" %>

<% if notice || alert %>
  <div class="<%= bg_color %> font-bold text-white px-4 py-2">
    <%= notice || alert %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="bg-white">
  <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
    <%= link_to "Bounty Hunter", root_path, class: "-m-1.5 p-1.5" %>

    <div class="flex lg:hidden">
      <button id="open_menu" type="button" class="border-0 hover:bg-transparent cursor-pointer -m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
        <span class="sr-only">Open main menu</span>

        <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
        </svg>
      </button>
    </div>

    <div class="hidden lg:flex lg:gap-x-12">
      <% if current_user %>
        <%= link_to "Browse",
          bounties_path,
          class: "text-sm/6 font-semibold text-gray-900" %>

        <%= link_to "Post",
          new_bounty_path,
          class: "text-sm/6 font-semibold text-gray-900" %>

        <%= link_to "Edit Profile",
          edit_user_path(current_user),
          class: "text-sm/6 font-semibold text-gray-900" %>

        <%= link_to "Log out",
          logout_path,
          class: "text-sm/6 font-semibold text-gray-900",
          data: { turbo_prefetch: false } %>
      <% else %>
        <%= link_to login_path, class: "text-sm/6 font-semibold text-gray-900" do %>
          Log in <span aria-hidden="true">&rarr;</span>
        <% end %>
      <% end %>
    </div>
  </nav>

  <!-- Mobile menu, show/hide based on menu open state. -->
  <div id="menu" class="hidden lg:hidden" role="dialog" aria-modal="true">
    <!-- Background backdrop, show/hide based on slide-over state. -->
    <div class="fixed inset-0 z-10"></div>

    <div class="fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
      <div class="flex items-center justify-between">
        <%= link_to "Bounty Hunter", root_path, class: "-m-1.5 p-1.5" %>

        <button id="close_menu" type="button" class="border-0 hover:bg-transparent cursor-pointer -m-2.5 rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Close menu</span>

          <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <div class="mt-6 flow-root">
        <div class="-my-6 divide-y divide-gray-500/10">
          <% if current_user %>
            <div class="space-y-2 py-6">
              <%= link_to "Browse",
                bounties_path,
                class: "-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50" %>

              <%= link_to "Post",
                new_bounty_path,
                class: "-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50" %>

              <%= link_to "Edit Profile",
                edit_user_path(current_user),
                class: "-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50" %>
            </div>
          <% end %>

          <div class="py-6">
            <% if current_user %>
              <%= link_to "Log out",
                logout_path,
                class: "-mx-3 block rounded-lg px-3 py-2.5 text-base/7 font-semibold text-gray-900 hover:bg-gray-50",
                data: { turbo_prefetch: false } %>
            <% else %>
              <%= link_to "Log in",
                login_path,
                class: "-mx-3 block rounded-lg px-3 py-2.5 text-base/7 font-semibold text-gray-900 hover:bg-gray-50" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bounty Hunter<%= " &bull; #{content_for(:title)}".html_safe if content_for?(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/flash" %>
    <%= render "layouts/header" %>

    <main class="p-4 w-full md:max-w-[600px]">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if errors.any? %>
  <div class="mt-4 text-red-600">
    <h2>Please fix <%= pluralize(errors.count, "error") %>:</h2>

    <ul>
      <% errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", errors: user.errors %>

<%= form_with(model: user) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <% if user.persisted? %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>

    <%= f.label :postal_code %>
    <%= f.text_field :postal_code %>
  <% end %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <div class="text-gray-500 text-sm italic">
    Password must be at least 8 characters,
    containing at least 1 uppercase letter,
    1 lowercase letter, 1 number,
    and 1 symbol (!, @, #, $, %, &amp;, *)
  </div>

  <%= f.submit user.new_record? ? "Sign up" : "Update", class: "mt-8" %>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

app/views/users/new.html.erb
<% content_for :title, "Sign up" %>

<h1>Sign up</h1>

<%= render "form", user: @user %>

<div class="mt-4">
  Already have an account?
  <%= link_to "Log in", login_path %>
</div>

app/views/welcome/show.html.erb
<% content_for :title, "Welcome" %>

<h1>Welcome to Bounty Hunter</h1>

<p>
  Got some odd jobs need doin&CloseCurlyQuote;?<br>
  Post the bounties that you&CloseCurlyQuote;re willing to pay for someone to do &OpenCurlyQuote;em!
</p>

<p>
  <% if current_user %>
    <%= link_to "Browse bounties", bounties_path %>
  <% else %>
    <%= link_to "Log in", login_path %> or
    <%= link_to "Sign up", signup_path %>
  <% end %>
</p>